// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParcelRegistry.Importer.Grb;

#nullable disable

namespace ParcelRegistry.Importer.Grb.Migrations
{
    [DbContext(typeof(ImporterContext))]
    [Migration("20230712082230_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ParcelRegistry.Importer.Grb.ProcessedRequests", b =>
                {
                    b.Property<string>("SHA256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("SHA256");

                    b.HasIndex("SHA256");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("SHA256"));

                    b.ToTable("ProcessedRequests", "GrbImporter");
                });

            modelBuilder.Entity("ParcelRegistry.Importer.Grb.RunHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FromDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ToDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("RunHistory", "GrbImporter");
                });
#pragma warning restore 612, 618
        }
    }
}
