name: Integration Tests

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    if: github.repository_owner == 'Informatievlaanderen'
    name: Run Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.VBR_DOTNET_VERSION_9 }}
          cache: true
          cache-dependency-path: "**/packages.lock.json"

      - name: .NET version
        shell: bash
        run: dotnet --info

      - name: Restore packages
        shell: bash
        run: |
          ./pre-restore.sh
          dotnet tool restore
          dotnet restore --locked-mode

      - name: Build
        shell: bash
        run: |
          dotnet build --nologo --no-restore --no-incremental --configuration Debug ParcelRegistry.sln

      - name: Test
        shell: bash
        run: |
          ln -s /usr/libexec/docker/cli-plugins/docker-compose /usr/local/bin/docker-compose
          dotnet test --nologo --no-build --filter 'FullyQualifiedName~IntegrationTests' ParcelRegistry.sln
        env:
          OAuth2IntrospectionOptions__ClientId: ${{ secrets.VBR_ACMIDM_INTROSPECTION_CLIENT_ID_TST }}
          OAuth2IntrospectionOptions__ClientSecret: ${{ secrets.VBR_ACMIDM_INTROSPECTION_CLIENT_SECRET_TST }}
          ClientId: ${{ secrets.VBR_ACMIDM_CLIENT_ID_TST }}
          ClientSecret: ${{ secrets.VBR_ACMIDM_CLIENT_SECRET_TST }}
